name: MiniCam

options:
  bundleIdPrefix: local.minicam
  deploymentTarget:
    macOS: "12.0"
  createIntermediateGroups: true
  projectFormat: xcode14_0
  xcodeVersion: "14.0"

settings:
  base:
    ARCHS: "$(ARCHS_STANDARD)"
    CODE_SIGN_IDENTITY: "-"
    CURRENT_PROJECT_VERSION: 1
    GENERATE_INFOPLIST_FILE: false
    MACOSX_DEPLOYMENT_TARGET: "12.0"
    MARKETING_VERSION: 0.1.0
    ONLY_ACTIVE_ARCH: false
    SWIFT_VERSION: "5.0"
  configs:
    Debug:
      ENABLE_DEBUG_DYLIB: false
      ONLY_ACTIVE_ARCH: true
    Release:
      ONLY_ACTIVE_ARCH: false

targets:
  MiniCam:
    type: application
    platform: macOS
    sources:
      - path: MiniCam
    info:
      path: MiniCam/Resources/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: local.minicam.app
        PRODUCT_NAME: MiniCam
    scheme:
      testTargets:
        - MiniCamTests

  MiniCamTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: MiniCamTests
    dependencies:
      - target: MiniCam
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        PRODUCT_BUNDLE_IDENTIFIER: local.minicam.tests
